### ISSUE TITLE
Dashboard for staff skills

### ISSUE THREAD

**Issue by gpimblott** [KainosSoftwareLtd/TechRadar#15]
A dashboard  graph that shows the total number of staff with skills in a technology would be useful

**Comment by adrianz-kainos** [comment]
@gpimblott 
What do you think about a bar graph? Bar colors could indicate different statuses of technology.
https://jsfiddle.net/ks0y2y8z/2
Or maybe you prefer something like a bubble chart?

**Comment by gpimblott** [comment]
I can’t access the picture ?

Gordon Pimblott MBCS CEng CITP | Solution Architect | Kainos  | Mob: 07772985560 | g.pimblott@kainos.com

**Comment by adrianz-kainos** [comment]
@gpimblott Oops, typo. It should work now.

**Comment by adrianz-kainos** [comment]
https://jsfiddle.net/ks0y2y8z/3/ 
This is the latest version of the graph. Let me know if you'd like me to use a different type of graph or to improve this one.

**Comment by gpimblott** [comment]
That's cool - If it's easy to do lets go with that
