### ISSUE TITLE
Dashboard Section

### ISSUE THREAD

**Issue by seamuss** [KainosSoftwareLtd/TechRadar#20]
Hi Folks,

Just some feedback on the dashboard section:
- Colour scheme of graphs needs be improved, very grey and hard to read at times.
- Responsiveness of graphs need to be improved, along with some of the axis that are squashed and becoming illegible at certain resolutions (specifically standard laptop resolution):
  <img width="1132" alt="screen shot 2016-10-03 at 12 23 18" src="https://cloud.githubusercontent.com/assets/6142980/19035868/34039490-8964-11e6-8fd1-f7c4b1a050b1.png">
- A great idea to visualise the overall data that is being captured, but need to make sure that it is represented properly, and also showing some useful insight that will allow people to look deeper.
- Need to think about the order of the graphs, it would seem that the "Most used Technologies" might be more important than "Top 10 voting users"
- Interesting to see when technologies have been used? where they popular 12 months ago, but usage has diminished etc. (Question generating visualisations)

**Comment by gpimblott** [comment]
Agreed - the graphs/dashboards were added as a quick fix to visualise the data.  They need to be improved and the value determined.
