### ISSUE TITLE
Licence information doesn't show in the header

### ISSUE THREAD

**Issue by piotrgo** [KainosSoftwareLtd/TechRadar#36]
After filling out licence information for given technology it's not being displayed in the header.

Screenshot below is "post save"

<img width="1189" alt="screen shot 2016-10-14 at 15 20 10" src="https://cloud.githubusercontent.com/assets/4050128/19390838/d43af316-9221-11e6-9061-d8aab58fc888.png">

**Comment by adrianz-kainos** [comment]
@piotrgo Thanks for all the feedback. Great attention to detail. :)
Can you check that one again? When I enter something into the "Technology licence type" field and  submit the form, it shows in the header. For me it seems to be working like intended. Example in the dev version:
https://k-tech-radar-dev.herokuapp.com/technology/28/edit

**Comment by xjedam** [comment]
Idd there is merit in displaying link only (when the person adding is unsure how to categorise the licence and has a link to it). #71 fixes that
