### ISSUE TITLE
Tech description overlaps with header 

### ISSUE THREAD

**Issue by piotrgo** [KainosSoftwareLtd/TechRadar#40]
<img width="334" alt="screen shot 2016-10-14 at 16 19 37" src="https://cloud.githubusercontent.com/assets/4050128/19392761/1465c77e-922a-11e6-86fc-a56215d35f17.png">

**Comment by adrianz-kainos** [comment]
@piotrgo Which browser did you use?

**Comment by piotrgo** [comment]
chrome, can't reproduce it anymore, so maybe something on my end.

**Comment by adrianz-kainos** [comment]
I managed to reproduce it with a technology that has a long description.
https://k-tech-radar.herokuapp.com/technology/190

It's caused by the long url on the right side of the description.
