### ISSUE TITLE
Reassign Technology Version doesn't work

### ISSUE THREAD

**Issue by gpimblott** [KainosSoftwareLtd/TechRadar#87]
I added Pyton to a project, with no version.  I then added a new version to Python and tried to update the existing entry for the project - It didn't work :(

I eventually deleted Python from the project and readded with the correct version

**Comment by xjedam** [comment]
Can't seem to reproduce the issue, could we have more details?

**Comment by xjedam** [comment]
Closing for now - can't reproduce locally, on dev env or on prod.
